### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by rstropek** [rstropek-teaching/pokelist-quiz-4ahif-brandart#1]
@brandart Thank you for your homework. I think, something went wrong. *app.js* contains much more code than *app.ts*. I guess you forgot to checkin your changes to *app.ts*. If you have questions regarding working with GitHub, let me know. I would be glad to help.

Greetings,
Rainer Stropek.

**Comment by brandart** [comment]
I had some problem with jQuery in Typescript, because everytime i wrote $, it got red underlined by the program, 
I couldn't find a solution, so therefor i just wrote everything in Javascript.
But I already know what my mistake was, I forget to install my types for jQuery..

In the contact homework, I already worked with Typescirpt

**Comment by rstropek** [comment]
Ah, ok.

Exactly. In such cases, install types using `npm install @types/<nameOfPackage>`.

Greetings,
Rainer Stropek.
